service: saeid-amn-simple-api-go
app: ${self:service}

frameworkVersion: "3"

useDotenv: true
# configValidationMode: error

provider:
  name: aws
  runtime: provided.al2023
  apiName: ${self:service}
  endpointType: EDGE
  #  stage: ${opt:stage, 'prod'}
  region: us-east-1
  environment:
    REGION: ${env:REGION}
    ENDPOINT_URL: ${env:ENDPOINT_URL}
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    DATABASE_TYPE: 'dynamodb'
    RUNNING_MODE: 'aws'
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}

#  logs:
#    http:
#      format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod", "routeKey":"$context.routeKey", "status":"$context.status","protocol":"$context.protocol", "responseLength":"$context.responseLength" }'
#    restApi:
# Enables HTTP access logs (default: true)
#      accessLogging: true
#      format: 'requestId: $context.requestId'
#
  iam:
    role: ${env:IAM_ROLE}

functions:
  create:
    handler: main
    events:
      - http:
          path: /api/devices/
          method: post
  get:
    handler: main
    events:
      - http:
          path: /api/devices/{id}
          method: get
  update:
    handler: main
    events:
      - http:
          path: /api/devices/{id}
          method: post

  delete:
    handler: main
    events:
      - http:
          path: /api/devices/{id}
          method: delete
#  list:
#    handler: main
#    events:
#      - http:
#          path: /api/devices
#          method: get

package:
  patterns:
    - '!/**'
    - bootstrap

#resources:
#  Resources:
#    TodosDynamoDbTable:
#      Type: 'AWS::DynamoDB::Table'
#      DeletionPolicy: Delete
#      Properties:
#        AttributeDefinitions:
#          -
#            AttributeName: id
#            AttributeType: S
#        KeySchema:
#          -
#            AttributeName: id
#            KeyType: HASH
#        BillingMode: PAY_PER_REQUEST
#        TableName: ${self:provider.environment.DYNAMODB_TABLE}